name: Commit and push
description: Set and validate package version in __init__.py, and check it doesn't already exist on PyPI.org
inputs:
  subject:
    description: First line of commit message
    required: false
    default: 'Prepare release ${VERSION}'
  push:
    description: If false, do not push changes
    required: false
    default: true
  quiet:
    description: If true, do not print git status
    required: false
    default: false
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        QUIET: ${{ inputs.quiet }}
        PUSH_CHANGES: ${{ inputs.push }}
      run: |
        if ! "$QUIET"; then
          git status
        fi
        git commit -m "Prepare release ${VERSION}" -m "Workflow: ${{ github.workflow}}, run: ${{ github.run_number }}"
        if "$PUSH_CHANGES"; then
          git push
        fi

      # Note: In the "checkout-pr-branch" action we set the "push.default" git config item to "current"
