name: Commit and push
description: Commit (staged files only by default) and push
inputs:
  message:
    description: Commit message
    required: false
    default: 'Prepare release ${VERSION}'
  all:
    description: If true, stage all files before comitting
    required: false
    default: false
  push:
    description: If false, do not push changes
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if ${{ inputs.all }}; then
          git add --all
        fi

        git status

        git commit -m "${{ inputs.message }}" -m "Workflow: ${{ github.workflow}}, run: ${{ github.run_number }}"
        if ${{ inputs.push }}; then
          git push
        fi

      # Note: In the "checkout-pr-branch" action we set the "push.default" git config item to "current"
